name: diegoremus
favicon: null
layout_spectrum: 0.4432947845198214
typography_spectrum: 0.576941633131355
title: Diego Remus cultivating innovation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2566639541182667
  lightness: 0.6092963984701782
  saturation: 0.4511656879913062
  rhythmicContrast: 0.521417110459879
purpose: []
